"""Windows forensic artifact collection modules."""

from . import (
    # Browser History
    chrome_history,
    edge_history,
    firefox_history,
    ie_history,
    # Registry Artifacts
    userassist,
    shimcache,
    bam,
    amcache,
    shellbags,
    typed_paths,
    run_keys,
    # System Artifacts
    process_list,
    network_connections,
    services,
    scheduled_tasks,
    startup_folders,
    environment_vars,
    hosts_file,
    # ESE Databases
    srum,
    windows_timeline,
    # File System Artifacts
    prefetch,
    jumplist,
    lnk_files,
    recycle_bin,
    mru_lists,
    psreadline,
    # Remote Access
    anydesk,
    teamviewer,
    # Collection-only artifacts
    event_logs,
    registry_system,
    registry_user,
    mft,
    usn_journal,
    ntfs_logfile,
    volume_shadow_copies,
    windows_firewall_log,
    wer_dumps,
    defender_logs,
    av_logs,
    rdp_cache,
    onedrive_logs,
    google_drive_logs,
    dropbox_metadata,
    iis_logs,
    windows_search_index,
    # Parsing artifacts
    arp_cache,
    dns_cache,
    net_sessions,
    handles,
    drivers,
    word_wheel_query,
    recent_files,
    usb_device_history,
    user_access_logging,
    wmi_persistence,
    bits_jobs,
    logmein,
    zone_identifier,
    recentfilecache,
    wifi_history,
)

ALL_ARTIFACTS = [
    chrome_history,
    edge_history,
    firefox_history,
    ie_history,
    userassist,
    shimcache,
    bam,
    amcache,
    shellbags,
    typed_paths,
    run_keys,
    process_list,
    network_connections,
    services,
    scheduled_tasks,
    startup_folders,
    environment_vars,
    hosts_file,
    srum,
    windows_timeline,
    prefetch,
    jumplist,
    lnk_files,
    recycle_bin,
    mru_lists,
    psreadline,
    anydesk,
    teamviewer,
    event_logs,
    registry_system,
    registry_user,
    mft,
    usn_journal,
    ntfs_logfile,
    volume_shadow_copies,
    windows_firewall_log,
    wer_dumps,
    defender_logs,
    av_logs,
    rdp_cache,
    onedrive_logs,
    google_drive_logs,
    dropbox_metadata,
    iis_logs,
    windows_search_index,
    arp_cache,
    dns_cache,
    net_sessions,
    handles,
    drivers,
    word_wheel_query,
    recent_files,
    usb_device_history,
    user_access_logging,
    wmi_persistence,
    bits_jobs,
    logmein,
    zone_identifier,
    recentfilecache,
    wifi_history,
]
